# DB setting
DIALECT = 'mysql'
USERNAME = 'root'
PASSWORD = '******'
HOST = '127.0.0.1'
PORT = '3306'
DATABASE = 'search_engine'

SQLALCHEMY_DATABASE_URI = '{}://{}:{}@{}:{}/{}?charset=utf8'.format(
  DIALECT, USERNAME, PASSWORD, HOST, PORT, DATABASE)

SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True

SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_MAX_OVERFLOW = 5